version: "3.9"
services:
  mongodb:
    container_name: mongo
    image: mongo:7.0.3-jammy
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ../.env
    command: [--auth]
    volumes:
      - ../db/scripts/dump/off/products.bson:/tmp/products.bson
      - ../config/mongod.conf:/etc/mongod.conf


